
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[349] =
    {   0,
        0,    0,    0,    0,    0,    0,   96,   89,   88,   79,
       89,   85,   78,   89,   89,    3,    4,   76,   74,   82,
       75,   89,   77,   86,   86,   81,   68,   80,   69,   85,
       85,    7,    8,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,    5,
       89,    6,   91,   92,   91,   93,   94,   71,    0,   83,
        0,   85,   85,   66,    0,    0,    0,    2,    1,   86,
        0,   86,   72,   70,   73,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   37,   85,
       85,   85,   85,   85,   85,   85,   85,   23,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   67,   90,   84,
        0,   87,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   44,   85,   85,   85,   11,   85,   85,
       13,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   64,   85,   85,
       85,    0,   85,   85,   85,   85,   85,   85,   85,   30,
       31,   85,   33,   85,   85,   85,   85,   85,   24,   39,
       85,   85,   85,   85,   45,   85,   85,   85,   85,   50,

       85,   27,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   60,   85,   85,    9,   19,   85,   85,
        0,   85,   85,   85,   85,   85,   85,   29,   32,   16,
       34,   85,   85,   85,   85,   10,   41,   43,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   55,   85,
       85,   57,   85,   85,   61,   85,   85,   25,    0,   85,
       20,   85,   85,   28,   85,   85,   85,   38,   85,   85,
       85,   47,   85,   85,   51,   85,   85,   85,   17,   22,
       18,   85,   58,   85,   62,   85,   85,   21,   85,    0,
       85,   12,   85,   36,   40,   42,   85,   85,   85,   52,

       53,   85,   85,   85,   85,   85,    0,    0,   26,   35,
       85,   85,   85,   85,   56,   85,   85,   65,    0,    0,
       85,   85,   49,   54,   85,   63,    0,    0,   46,   48,
       85,    0,    0,   85,    0,    0,   59,    0,    0,    0,
        0,    0,    0,   15,    0,    0,   14,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    5,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   23,
        5,    5,   24,    5,    5,    5,    5,    5,    5,    5,
        5,    5,   25,    5,    5,    5,    5,   26,    5,    5,
       27,   28,   29,    1,    5,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,    5,   39,   40,   41,   42,
       43,   44,    5,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    1,    1,
        1,    1,    5,    3,    3,    3,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[356] =
    {   0,
        0,    0,   55,   56,  316,  312,  312,  995,  995,  287,
       55,   43,  995,  299,  269,  995,  995,  995,  995,  995,
      995,  252,   52,   45,   47,  995,  262,  250,  243,   52,
       55,  995,  995,   57,   61,   68,   75,   59,   97,   73,
      103,  105,  112,  132,   63,  116,  114,  138,  152,  995,
      207,  995,  995,  995,  239,  995,  995,  995,   91,  995,
        0,  107,    0,  995,  244,  240,  212,  995,  995,  205,
        0,  140,  995,  995,  995,  154,  157,  161,  165,  167,
      169,  174,  176,  178,  180,  186,  188,  182,  197,  201,
      203,  209,  214,  211,  216,  218,  220,  222,  224,  226,

      232,  240,  243,  248,  252,  258,  260,  262,  264,  268,
      272,  277,  282,  285,  287,  293,  302,  995,  995,  995,
      167,    0,  304,  308,  310,  319,  324,  327,  330,  334,
      336,  332,  338,  344,  354,  356,  358,  360,  362,  364,
      367,  374,  378,  370,  388,  392,  394,  399,  401,  404,
      397,  406,  408,  410,  421,  412,  426,  431,  433,  437,
      439,  443,  445,  447,  449,  452,  454,  461,  464,  466,
      468,  154,  481,  483,  485,  487,  489,  492,  494,  496,
      498,  503,  505,  510,  512,  519,  521,  524,  526,  528,
      530,  532,  534,  536,  543,  545,  550,  558,  553,  560,

      563,  567,  569,  572,  574,  576,  579,  583,  587,  589,
      592,  599,  601,  605,  609,  611,  615,  617,  622,  624,
      141,  626,  628,  630,  632,  634,  636,  638,  650,  655,
      657,  659,  662,  665,  667,  669,  671,  673,  675,  677,
      679,  687,  689,  691,  695,  697,  700,  702,  708,  713,
      716,  718,  720,  722,  729,  731,  733,  735,  139,  737,
      741,  747,  755,  743,  759,  761,  763,  766,  768,  771,
      773,  775,  779,  782,  777,  785,  787,  798,  800,  807,
      809,  811,  813,  815,  817,  819,  821,  995,  825,  130,
      830,  832,  834,  837,  839,  842,  845,  847,  852,  849,

      854,  856,  858,  861,  865,  871,  123,  117,  868,  874,
      876,  878,  880,  882,  891,  893,  895,  899,  131,  107,
      901,  908,  910,  912,  915,  917,  107,  132,  919,  921,
      923,   97,   97,  927,  105,   91,  931,  104,   88,   75,
       70,   53,   42,  995,   47,   42,  995,  995,  968,  973,
      978,  981,  986,  989,   77
    } ;

static yyconst flex_int16_t yy_def[356] =
    {   0,
      348,    1,  349,  349,  350,  350,  348,  348,  348,  348,
      351,  352,  348,  348,  353,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  352,
      352,  348,  348,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  351,  348,
      351,  352,  354,  348,  348,  353,  348,  348,  348,  348,
      355,  348,  348,  348,  348,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  348,  348,  348,
      348,  355,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  348,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      348,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  348,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  348,  352,  348,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  348,  348,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  348,  348,
      352,  352,  352,  352,  352,  352,  348,  348,  352,  352,
      352,  348,  348,  352,  348,  348,  352,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,    0,  348,  348,
      348,  348,  348,  348,  348
    } ;

static yyconst flex_int16_t yy_nxt[1052] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   12,   30,   31,   12,   32,    8,   33,   34,
       35,   36,   37,   38,   39,   40,   12,   41,   12,   42,
       12,   43,   12,   44,   45,   46,   47,   12,   48,   49,
       12,   12,   12,   50,   51,   52,   54,   54,   60,   63,
       63,   70,   68,   72,   72,   55,   55,   69,   63,   63,
       71,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,  122,   61,  347,   63,   63,  346,   79,  345,   63,
       63,   63,   63,   76,   60,   71,  108,   84,   90,  344,

       91,   77,   80,   81,   85,   82,   78,   86,   88,   92,
       87,  343,   83,   63,   63,   97,  342,   89,   61,   63,
       63,   63,   63,   63,   63,  341,   93,  340,   63,   63,
       63,   63,   63,   63,   94,  339,   95,   98,  338,   96,
      336,  102,  335,   99,  100,  103,  333,  101,   63,   63,
      114,  332,  109,  328,   63,   63,   72,   72,  115,  104,
      327,  105,  110,  111,  320,  112,  319,  113,   63,   63,
       63,   63,  308,   63,   63,  288,  106,   63,   63,  107,
      116,   63,   63,   63,   63,   63,   63,  259,  117,  221,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

      123,  124,   63,   63,   63,   63,  125,  129,  172,  133,
      126,  128,  127,   63,   63,  134,  136,   63,   63,   63,
       63,   70,  130,  131,  132,   63,   63,   63,   63,  135,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,  137,  121,  138,   65,   63,   63,
      139,  120,  142,  141,  119,  140,   63,   63,  143,   63,
       63,  118,  144,   75,   63,   63,  145,  146,   63,   63,
       74,  147,  148,  149,   63,   63,   63,   63,   63,   63,
       63,   63,   73,  153,   63,   63,  150,  152,   63,   63,
      156,   67,  151,   63,   63,  154,   66,  159,   63,   63,

      155,   63,   63,   63,   63,   64,  158,   58,  157,   63,
       63,  348,  160,   57,  162,  161,  166,   57,   63,   63,
       63,   63,  164,  163,   63,   63,   63,   63,  348,  165,
      169,  348,  170,  348,  167,   63,   63,  173,  168,  171,
       63,   63,  348,   63,   63,  174,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,  175,  177,  348,  179,
       63,   63,  348,  182,  348,  176,  178,  180,  348,  181,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,  183,   63,   63,  187,   63,   63,  188,  184,
       63,   63,  348,  189,   63,   63,  348,  191,  348,  185,

      186,  348,  190,  193,   63,   63,  348,  194,   63,   63,
       63,   63,  192,   63,   63,   63,   63,   63,   63,  348,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
      195,  196,  199,  348,  197,  348,  200,   63,   63,  348,
      198,  201,   63,   63,  348,  202,  203,   63,   63,   63,
       63,  206,  348,   63,   63,   63,   63,  348,  204,   63,
       63,   63,   63,   63,   63,   63,   63,  205,   63,   63,
       63,   63,  211,  207,  210,  208,  213,   63,   63,  209,
       63,   63,   63,   63,   63,   63,  348,  217,  348,  212,
      348,  215,  214,  216,  348,  219,  218,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,  220,   63,   63,
       63,   63,   63,   63,   63,   63,  222,  348,  224,   63,
       63,   63,   63,  348,  223,  227,   63,   63,   63,   63,
      348,  225,  228,  226,  348,   63,   63,   63,   63,  229,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,  348,  230,  232,  348,  231,   63,
       63,   63,   63,  234,  348,  236,   63,   63,  233,   63,
       63,  235,  348,  237,   63,   63,   63,   63,  239,   63,
       63,  348,  238,   63,   63,   63,   63,  241,   63,   63,
       63,   63,   63,   63,  240,   63,   63,  242,  244,   63,

       63,  245,  348,   63,   63,   63,   63,  246,   63,   63,
      348,  243,  348,  247,  348,   63,   63,   63,   63,  348,
      251,   63,   63,  248,  250,   63,   63,   63,   63,  249,
      253,   63,   63,   63,   63,  348,  252,  254,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,  256,  258,  255,  260,
      348,  263,  348,  261,  348,  265,   63,   63,  257,  348,
      262,   63,   63,   63,   63,   63,   63,  348,   63,   63,
      264,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,  348,  268,  269,

      266,  267,  348,   63,   63,   63,   63,   63,   63,  348,
      270,   63,   63,   63,   63,  271,   63,   63,   63,   63,
      273,  274,  275,  272,   63,   63,  276,  348,  278,   63,
       63,  279,   63,   63,   63,   63,   63,   63,   63,   63,
      348,  277,  348,  280,  281,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,  348,  283,   63,   63,   63,
       63,  290,  282,   63,   63,  348,  284,  348,  286,  348,
      287,   63,   63,  348,  285,   63,   63,   63,   63,   63,
       63,  289,   63,   63,   63,   63,  291,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,  348,   63,   63,

      292,   63,   63,   63,   63,  348,  297,  348,  293,  294,
      298,  299,  348,  295,   63,   63,   63,   63,  300,  348,
      301,  348,  296,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,  307,
      348,   63,   63,  348,  302,  303,   63,   63,   63,   63,
       63,   63,  305,   63,   63,   63,   63,  304,   63,   63,
      306,   63,   63,   63,   63,   63,   63,  310,   63,   63,
       63,   63,   63,   63,   63,   63,  309,   63,   63,  348,
      312,   63,   63,  313,   63,   63,  311,   63,   63,  314,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

      348,  315,  316,  348,  318,  348,  317,   63,   63,   63,
       63,   63,   63,  323,  324,   63,   63,   63,   63,  348,
      322,  348,  321,  348,   63,   63,   63,   63,   63,   63,
      325,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,  326,  330,   63,   63,  348,  329,   63,   63,  348,
      348,  348,  348,  348,  348,  348,  334,  348,  348,  337,
      348,  348,  348,  348,  348,  348,  348,  331,   53,   53,
       53,   53,   53,   56,   56,   56,   56,   56,   59,  348,
       59,   59,   59,   62,  348,   62,   65,  348,   65,  348,
       65,   63,  348,   63,    7,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348
    } ;

static yyconst flex_int16_t yy_chk[1052] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   11,   12,
       12,   24,   23,   25,   25,    3,    4,   23,   30,   30,
       24,   31,   31,   34,   34,   38,   38,   35,   35,   45,
       45,  355,   11,  346,   36,   36,  345,   34,  343,   40,
       40,   37,   37,   30,   59,   24,   45,   36,   38,  342,

       38,   31,   34,   35,   36,   35,   31,   36,   37,   38,
       36,  341,   35,   39,   39,   40,  340,   37,   59,   41,
       41,   42,   42,   62,   62,  339,   39,  338,   43,   43,
       47,   47,   46,   46,   39,  336,   39,   41,  335,   39,
      333,   43,  332,   41,   41,   43,  328,   42,   44,   44,
       47,  327,   46,  320,   48,   48,   72,   72,   47,   43,
      319,   44,   46,   46,  308,   46,  307,   46,   49,   49,
       76,   76,  290,   77,   77,  259,   44,   78,   78,   44,
       48,   79,   79,   80,   80,   81,   81,  221,   49,  172,
       82,   82,   83,   83,   84,   84,   85,   85,   88,   88,

       76,   77,   86,   86,   87,   87,   78,   82,  121,   85,
       79,   81,   80,   89,   89,   86,   88,   90,   90,   91,
       91,   70,   83,   84,   84,   92,   92,   94,   94,   87,
       93,   93,   95,   95,   96,   96,   97,   97,   98,   98,
       99,   99,  100,  100,   89,   67,   90,   66,  101,  101,
       91,   65,   94,   93,   55,   92,  102,  102,   95,  103,
      103,   51,   96,   29,  104,  104,   97,   99,  105,  105,
       28,  100,  100,  101,  106,  106,  107,  107,  108,  108,
      109,  109,   27,  105,  110,  110,  102,  104,  111,  111,
      107,   22,  103,  112,  112,  106,   15,  110,  113,  113,

      106,  114,  114,  115,  115,   14,  109,   10,  108,  116,
      116,    7,  110,    6,  112,  111,  115,    5,  117,  117,
      123,  123,  114,  113,  124,  124,  125,  125,    0,  114,
      116,    0,  116,    0,  115,  126,  126,  123,  115,  117,
      127,  127,    0,  128,  128,  124,  129,  129,  132,  132,
      130,  130,  131,  131,  133,  133,  125,  127,    0,  129,
      134,  134,    0,  132,    0,  126,  128,  130,    0,  131,
      135,  135,  136,  136,  137,  137,  138,  138,  139,  139,
      140,  140,  133,  141,  141,  136,  144,  144,  137,  134,
      142,  142,    0,  138,  143,  143,    0,  140,    0,  135,

      135,    0,  139,  142,  145,  145,    0,  143,  146,  146,
      147,  147,  141,  151,  151,  148,  148,  149,  149,    0,
      150,  150,  152,  152,  153,  153,  154,  154,  156,  156,
      145,  146,  148,    0,  146,    0,  149,  155,  155,    0,
      147,  150,  157,  157,    0,  152,  153,  158,  158,  159,
      159,  156,    0,  160,  160,  161,  161,    0,  154,  162,
      162,  163,  163,  164,  164,  165,  165,  155,  166,  166,
      167,  167,  161,  157,  160,  158,  163,  168,  168,  159,
      169,  169,  170,  170,  171,  171,    0,  167,    0,  162,
        0,  165,  164,  166,    0,  170,  169,  173,  173,  174,

      174,  175,  175,  176,  176,  177,  177,  171,  178,  178,
      179,  179,  180,  180,  181,  181,  173,    0,  175,  182,
      182,  183,  183,    0,  174,  178,  184,  184,  185,  185,
        0,  176,  179,  177,    0,  186,  186,  187,  187,  182,
      188,  188,  189,  189,  190,  190,  191,  191,  192,  192,
      193,  193,  194,  194,    0,  184,  186,    0,  185,  195,
      195,  196,  196,  188,    0,  192,  197,  197,  187,  199,
      199,  191,    0,  193,  198,  198,  200,  200,  196,  201,
      201,    0,  194,  202,  202,  203,  203,  198,  204,  204,
      205,  205,  206,  206,  197,  207,  207,  199,  203,  208,

      208,  204,    0,  209,  209,  210,  210,  205,  211,  211,
        0,  201,    0,  206,    0,  212,  212,  213,  213,    0,
      210,  214,  214,  207,  209,  215,  215,  216,  216,  208,
      212,  217,  217,  218,  218,    0,  211,  213,  219,  219,
      220,  220,  222,  222,  223,  223,  224,  224,  225,  225,
      226,  226,  227,  227,  228,  228,  216,  220,  215,  222,
        0,  225,    0,  223,    0,  227,  229,  229,  219,    0,
      224,  230,  230,  231,  231,  232,  232,    0,  233,  233,
      226,  234,  234,  235,  235,  236,  236,  237,  237,  238,
      238,  239,  239,  240,  240,  241,  241,    0,  234,  235,

      232,  233,    0,  242,  242,  243,  243,  244,  244,    0,
      237,  245,  245,  246,  246,  239,  247,  247,  248,  248,
      241,  242,  243,  240,  249,  249,  244,    0,  246,  250,
      250,  247,  251,  251,  252,  252,  253,  253,  254,  254,
        0,  245,    0,  248,  250,  255,  255,  256,  256,  257,
      257,  258,  258,  260,  260,    0,  253,  261,  261,  264,
      264,  262,  251,  262,  262,    0,  254,    0,  256,    0,
      257,  263,  263,    0,  255,  265,  265,  266,  266,  267,
      267,  260,  268,  268,  269,  269,  263,  270,  270,  271,
      271,  272,  272,  275,  275,  273,  273,    0,  274,  274,

      265,  276,  276,  277,  277,    0,  271,    0,  266,  267,
      273,  274,    0,  269,  278,  278,  279,  279,  276,    0,
      277,    0,  270,  280,  280,  281,  281,  282,  282,  283,
      283,  284,  284,  285,  285,  286,  286,  287,  287,  289,
        0,  289,  289,    0,  278,  282,  291,  291,  292,  292,
      293,  293,  286,  294,  294,  295,  295,  284,  296,  296,
      287,  297,  297,  298,  298,  300,  300,  293,  299,  299,
      301,  301,  302,  302,  303,  303,  291,  304,  304,    0,
      298,  305,  305,  299,  309,  309,  297,  306,  306,  302,
      310,  310,  311,  311,  312,  312,  313,  313,  314,  314,

        0,  303,  304,    0,  306,    0,  305,  315,  315,  316,
      316,  317,  317,  313,  314,  318,  318,  321,  321,    0,
      312,    0,  311,    0,  322,  322,  323,  323,  324,  324,
      316,  325,  325,  326,  326,  329,  329,  330,  330,  331,
      331,  317,  322,  334,  334,    0,  321,  337,  337,    0,
        0,    0,    0,    0,    0,    0,  331,    0,    0,  334,
        0,    0,    0,    0,    0,    0,    0,  325,  349,  349,
      349,  349,  349,  350,  350,  350,  350,  350,  351,    0,
      351,  351,  351,  352,    0,  352,  353,    0,  353,    0,
      353,  354,    0,  354,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ijscanner.l"
#line 2 "ijscanner.l"
	int in_comment = 0;
	int in_dash_comment = 0;
	int linha=0;
	int coluna=0;
	int linhaerro=0;
	int colunaerro=0;
	void conta();
	int ilegallcaracter;

#line 808 "lex.yy.c"

#define INITIAL 0
#define IN_COMMENT 1
#define DASH_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 14 "ijscanner.l"

#line 994 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 349 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 995 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "ijscanner.l"
{conta(); BEGIN DASH_COMMENT; in_dash_comment = 1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "ijscanner.l"
{conta(); BEGIN IN_COMMENT; in_comment = 1; linhaerro = linha; colunaerro = coluna-2;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "ijscanner.l"
{conta(); printf("OCURV\n");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "ijscanner.l"
{conta();printf("CCURV\n");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "ijscanner.l"
{conta();printf("OBRACE\n");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "ijscanner.l"
{conta();printf("CBRACE\n");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "ijscanner.l"
{conta();printf("OSQUARE\n");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "ijscanner.l"
{conta();printf("CSQUARE\n");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "ijscanner.l"
{conta();printf("BOOLLIT(%s)\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "ijscanner.l"
{conta();printf("BOOLLIT(%s)\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "ijscanner.l"
{conta();printf("INT\n");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "ijscanner.l"
{conta();printf("BOOL\n");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "ijscanner.l"
{conta();printf("NEW\n");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "ijscanner.l"
{conta();printf("PRINT\n");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "ijscanner.l"
{conta();printf("PARSEINT\n");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "ijscanner.l"
{conta();printf("CLASS\n");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "ijscanner.l"
{conta();printf("PUBLIC\n");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "ijscanner.l"
{conta();printf("STATIC\n");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "ijscanner.l"
{conta();printf("VOID\n");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "ijscanner.l"
{conta();printf("STRING\n");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "ijscanner.l"
{conta();printf("DOTLENGTH\n");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "ijscanner.l"
{conta();printf("RETURN\n");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "ijscanner.l"
{conta();printf("IF\n");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "ijscanner.l"
{conta();printf("ELSE\n");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "ijscanner.l"
{conta();printf("WHILE\n");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 57 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 58 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 59 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 60 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 61 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 62 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 63 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 64 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 65 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 66 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 67 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 68 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 69 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 70 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 71 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 72 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 73 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 74 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 75 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 76 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 77 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 78 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 79 "ijscanner.l"
{conta();printf("RESERVED(%s)\n", yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 80 "ijscanner.l"
{conta();printf("OP1(%s)\n", yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 81 "ijscanner.l"
{conta();printf("OP1(%s)\n", yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 82 "ijscanner.l"
{conta();printf("OP2(%s)\n", yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 83 "ijscanner.l"
{conta();printf("OP2(%s)\n", yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 84 "ijscanner.l"
{conta();printf("OP2(%s)\n", yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 85 "ijscanner.l"
{conta();printf("OP2(%s)\n", yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 86 "ijscanner.l"
{conta();printf("OP2(%s)\n", yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 87 "ijscanner.l"
{conta();printf("OP2(%s)\n", yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 88 "ijscanner.l"
{conta();printf("OP3(%s)\n", yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 89 "ijscanner.l"
{conta();printf("OP3(%s)\n", yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 90 "ijscanner.l"
{conta();printf("OP4(%s)\n", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 91 "ijscanner.l"
{conta();printf("OP4(%s)\n", yytext);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 92 "ijscanner.l"
{conta();printf("OP4(%s)\n", yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 93 "ijscanner.l"
{conta();printf("NOT\n");}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 94 "ijscanner.l"
{conta();printf("ASSIGN\n");}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 95 "ijscanner.l"
{conta();printf("SEMIC\n");}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 96 "ijscanner.l"
{conta();printf("COMMA\n");}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 97 "ijscanner.l"
{conta();printf("STRLIT(%s)\n", yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 98 "ijscanner.l"
{conta();printf("CHRLIT(%s)\n", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 99 "ijscanner.l"
{conta();printf("ID(%s)\n", yytext);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 100 "ijscanner.l"
{conta();printf("INTLIT(%s)\n", yytext);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 101 "ijscanner.l"
{conta();printf("INTLIT(%s)\n", yytext);}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 102 "ijscanner.l"
{conta();}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 103 "ijscanner.l"
{printf("Line %d, col %d: illegal character ('%c')\n",linha+1,coluna+1,yytext[0]);conta();}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 104 "ijscanner.l"
{conta();BEGIN INITIAL; in_comment = 0;};	
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 105 "ijscanner.l"
{conta();};	
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 106 "ijscanner.l"
{conta();};
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 107 "ijscanner.l"
{conta();};
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 108 "ijscanner.l"
{conta();BEGIN INITIAL; in_comment = 0;};
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 111 "ijscanner.l"
ECHO;
	YY_BREAK
#line 1555 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_COMMENT):
case YY_STATE_EOF(DASH_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 349 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 349 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 348);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 111 "ijscanner.l"



int main()
{
	yylex();
	return 0;
}

int yywrap()
{
	if(in_comment) {
		printf ("Line %d, col %d: unterminated comment\n", linhaerro+1, colunaerro+1);
	}
	return 1;
}

void conta()
{
	int i;
	for(i = 0; yytext[i] != '\0'; i++){
		if (yytext[i] == '\n'){
			linha++;
			coluna = 0;
		}
		
		else
			coluna++;
	}
}

